#-------------------------------------------------------------------------------
# JARVIS macros
#-------------------------------------------------------------------------------

MACRO(JARVIS_SETUP_TARGET target subsystem)
IF(WIN32)
	IF(MSVC)
		SET_TARGET_PROPERTIES(${target}
			PROPERTIES 
			COMPILE_FLAGS "/Ycconfig.h /Fp${CMAKE_CFG_INTDIR}/${target}/config.pch")
	ENDIF()
ELSEIF(APPLE)
	SET_TARGET_PROPERTIES(${target} PROPERTIES XCODE_ATTRIBUTE_GCC_PREFIX_HEADER "src/core/config.h")
	SET_TARGET_PROPERTIES(${target} PROPERTIES XCODE_ATTRIBUTE_LLVM_LTO[variant=Release] YES)
	SET_TARGET_PROPERTIES(${target} PROPERTIES XCODE_ATTRIBUTE_GCC_OPTIMIZATION_LEVEL[variant=Release] "fast")
ELSE()

SET_TARGET_PROPERTIES(${target} PROPERTIES FOLDER $<TARGET_FILE_DIR:target>)
SET_TARGET_PROPERTIES(${target} PROPERTIES DEBUG_POSTFIX ".debug")
        
SET_TARGET_PROPERTIES(${target} PROPERTIES PDB_OUTPUT_DIRECTORY_DEBUG ${CMAKE_BINARY_DIR}/pdb)
SET_TARGET_PROPERTIES(${target} PROPERTIES PDB_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/pdb)
SET_TARGET_PROPERTIES(${target} PROPERTIES PDB_OUTPUT_DIRECTORY_RELWITHDEBINFO ${CMAKE_BINARY_DIR}/pdb)
SET_TARGET_PROPERTIES(${target} PROPERTIES PDB_OUTPUT_DIRECTORY_RELEASE ${CMAKE_BINARY_DIR}/pdb)
ENDIF()

SET_TARGET_PROPERTIES(${target} PROPERTIES FOLDER "JARVIS")

IF(WIN32)
	IF(${subsystem} STREQUAL Windows)
		SET_TARGET_PROPERTIES(${target}
			PROPERTIES
			WIN32_EXECUTABLE ON
		)
		TARGET_COMPILE_DEFINITIONS(${target} PRIVATE "__J_EXE_WINDOWS__=1")
	ELSEIF(${subsystem} STREQUAL Console)
		SET_TARGET_PROPERTIES(${target}
			PROPERTIES
			WIN32_EXECUTABLE OFF
		)
		TARGET_COMPILE_DEFINITIONS(${target} PRIVATE "__J_EXE_WINDOWS__=0")
	ELSEIF(${subsystem} STREQUAL Library)
		TARGET_COMPILE_DEFINITIONS(${target} PRIVATE "__J_EXE_WINDOWS__=0")
	ENDIF()
ENDIF()

ENDMACRO(JARVIS_SETUP_TARGET)

MACRO(JARVIS_SETUP_TARGET_CUSTOM_PCH target pch)
IF(WIN32)
	IF(MSVC)
		SET_TARGET_PROPERTIES(${target}
			PROPERTIES 
			COMPILE_FLAGS "/Yc${pch}.h /Fp${CMAKE_CFG_INTDIR}/${target}/config.pch")
	ENDIF()
ELSEIF(APPLE)
	SET_TARGET_PROPERTIES(${target} PROPERTIES XCODE_ATTRIBUTE_GCC_PREFIX_HEADER {pch})
	SET_TARGET_PROPERTIES(${target} PROPERTIES XCODE_ATTRIBUTE_LLVM_LTO[variant=Release] YES)
	SET_TARGET_PROPERTIES(${target} PROPERTIES XCODE_ATTRIBUTE_GCC_OPTIMIZATION_LEVEL[variant=Release] "fast")
ELSE()


ENDMACRO(JARVIS_SETUP_TARGET_CUSTOM_PCH)
